export const CHANGE_SORT_ID = "CHANGE_SORT_ID"
export const CHANGE_FILTER_ID = "CHANGE_FILTER_ID"
export const FETCHING_IS_ON = "FETCHING_IS_ON"
export const GET_SEARCH_RESULTS = "GET_SEARCH_RESULTS"

